### ISSUE TITLE
Appears to not work if you have allowJs on in tsconfig json

### ISSUE THREAD

**Issue by JeronimoFictiv** [allegro/typescript-strict-plugin#14]
Running this on a project that has allowJs on in the tsconfig json and has js files appears to trigger this error. I turned off allowJs and it seems to run.

```
yarn run v1.10.1
$ tsc-strict
⠦ Looking for strict files...(node:25319) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: tsc --listFilesOnly
error TS5055: Cannot write file '/Users/.../redacted.js' because it would overwrite input file.
...
 at makeError (/Users/.../node_modules/typescript-strict-plugin/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/.../node_modules/typescript-strict-plugin/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.listFilesOnly (/Users/.../node_modules/typescript-strict-plugin/dist/cli/lib/typescript.js:9:20)
    at async getFilesCheckedByTs (/Users/.../node_modules/typescript-strict-plugin/dist/cli/lib/strictFiles.js:28:30)
    at async findStrictFiles (/Users/.../node_modules/typescript-strict-plugin/dist/cli/lib/strictFiles.js:34:30)
    at async waitWithSpinner (/Users/.../node_modules/typescript-strict-plugin/dist/cli/find-strict-errors.js:36:28)
    at async Object.findStrictErrors (/Users/.../node_modules/typescript-strict-plugin/dist/cli/find-strict-errors.js:13:29)
    at async run (/Users/.../node_modules/typescript-strict-plugin/dist/cli/cli.js:10:20)
(node:25319) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25319) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠴ Looking for strict files...
```

**Comment by kamkry** [comment]
Hi, we couldn't reproduce this error, could you share your tsconfig.json and version of typescript?
